### PR TITLE
New style readme [skip ci]

### PR DESCRIPTION
**Pull request by jsignell**
Not sure if you'll want the coverage row in there. 

image

### CODE REVIEW

**Comment by jsignell** [comment]
Is this ok with you @philippjfr

**Comment by philippjfr** [comment]
Yes, thanks.

**Comment by jbednar** [comment]
Can we find a standard way to make a link to the overall status dashboard that shows all the PyViz projects?  It would be nice if each project had a link back both to pyviz.org and also to status.pyviz.org in the same place on each project.

**Comment by jsignell** [comment]
Maybe there should be an "About Pyviz" section at the end of each readme

**Comment by jbednar** [comment]
That would probably work:

# About PyViz

<project_name> is part of the PyViz initiative for making Python-based visualization tools work well together.  See [pyviz.org](http://pyviz.org) for related packages that you can use with <project_name> and [status.pyviz.org](http://status.pyviz.org) for the current status of each PyViz project.

**Pull request merged**
