### PR TITLE
Exposing plot at top level

### PR DESCRIPTION
**Pull request by jsignell**
```python
import numpy as np
import pandas as pd

pd.options.plotting.backend = 'hvplot'
data = np.random.normal(size=[50, 2])
df = pd.DataFrame(data, columns=['x', 'y'])

df.plot(x='x', y='y')
```

### CODE REVIEW

**Comment by jbednar** [comment]
How does that example depend on having plot at the top level?

**Comment by jsignell** [comment]
This is from the gitter convo

**Comment by jsignell** [comment]
There are two ways to implement backends for `pd.options.plotting.backend `: entrypoints or exposing a top level plot function in the module.

**Comment by jbednar** [comment]
To summarize the conversation from gitter for posterity, the issue is that `pd.options.plotting.backend = 'holoviews'` currently works, via the entry point mechanism, but `pd.options.plotting.backend = 'hvplot'` does not.  With this PR, `pd.options.plotting.backend = 'hvplot'` now works, via the top-level plot function method.

**Pull request merged**
