### PR TITLE
Alternative implementation to aspect handling

### PR DESCRIPTION
**Pull request by philippjfr**
Alternative to #268 
Closes: #192 
Closes: #75

### CODE REVIEW

**Comment by jsignell** [comment]
Screen Shot 2019-08-02 at 11 42 09 AM

**Comment by jsignell** [comment]
Screen Shot 2019-08-02 at 11 52 34 AM

**Comment by jsignell** [comment]
I think it's time for me to start writing tests. But this is what I'm looking at:

Screen Shot 2019-08-02 at 12 04 45 PM

**Comment by jsignell** [comment]
```python
import xarray as xr
import hvplot.xarray

da = xr.tutorial.open_dataset('air_temperature').isel(time=0)

pn.Column(
    pn.Row(
        da.hvplot.image(aspect=1, height=150),
        da.hvplot.image(aspect=1, height=150, rasterize=True),
        da.hvplot.image(aspect=1, height=150, rasterize=True, dynamic=False)
    ),
    pn.Row(
        da.hvplot.image(data_aspect=2, height=150), 
        da.hvplot.image(data_aspect=2, height=150, rasterize=True), 
        da.hvplot.image(data_aspect=2, height=150, rasterize=True, dynamic=False)
    ),
    pn.Row(
        da.hvplot.image(geo=True, height=150), 
        da.hvplot.image(geo=True, height=150, rasterize=True), 
        da.hvplot.image(geo=True, height=150, rasterize=True, dynamic=False)
    ),
)   
```

**Comment by jsignell** [comment]
I think this is done. Shall I merge?

**Comment by jsignell** [comment]
Closes: #192
Closes: #75

**Comment by philippjfr** [comment]
Thanks for the tests @jsignell

**Pull request merged**
