### PR TITLE
Allow datashade/rasterize even when c is same as x or y

### PR DESCRIPTION
**Pull request by jsignell**
Closes: #226 

Note that this PR also fixes some instances of hvplot altering the input data.

```python
import holoviews as hv
import hvplot.pandas
from bokeh.sampledata.autompg import autompg
hv.extension('bokeh')
autompg.hvplot.scatter(x='mpg', y='yr', c='yr', datashade=True, dynspread=True)
autompg.hvplot.scatter(x='mpg', y='yr', c='yr', rasterize=True, y_sampling=1, x_sampling=1)
```

Screen Shot 2019-08-05 at 1 42 35 PM

### CODE REVIEW

**Comment by philippjfr** [comment]
LGTM

**Comment by philippjfr** [comment]
Oh, it's still WIP, nvm.

**Comment by jsignell** [comment]
Yeah now it's ready. I was still cleaning up logic and adding tests. The only dangling bit now is that the _color field is included in the hover. Not sure how to turn that off.

**Comment by jsignell** [comment]
Ok if I merge?

**Pull request merged**
