### PR TITLE
Removed some unused imports

### PR DESCRIPTION
**Pull request by ceball**
Removed some unused imports.

Wasn't sure if it's ok to remove the intake import or not in Plotting.ipynb?

-----

Ignore deliberate side effect imports:

```
diff --git a/tox.ini b/tox.ini
index 8ab9e46..25834a4 100644
--- a/tox.ini
+++ b/tox.ini
@@ -73,7 +73,8 @@ norecursedirs = doc .git dist build _build .ipynb_checkpoints
 #                   .*gallery/bokeh/xarray_gridded\.ipynb$
 #                   .*gallery/.*/xarray_image\.ipynb$
 #                   .*gallery/.*/xarray_quadmesh\.ipynb$
-
+nbsmoke_flakes_to_ignore = .*hvplot\..* imported but unused.*
+
 [flake8]
 include = *.py
 # run_tests.py is generated by conda build, which appears to have a
```

```
(nbsdev) D:\code\pyviz\hvplot>pytest -v --nbsmoke-lint --nbsmoke-lint-debug examples
=============================================================== test session starts ================================================================
platform win32 -- Python 3.6.8, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- d:\venvs\nbsdev\scripts\python.exe
cachedir: .pytest_cache
rootdir: D:\code\pyviz\hvplot, inifile: tox.ini
plugins: cov-2.7.1, nbsmoke-0.2.8.post44+gbdfd485
collected 11 items / 22 skipped

examples/homepage.ipynb::D:\code\pyviz\hvplot\examples\homepage.ipynb PASSED                                                                  [  9%]
examples/user_guide/Customization.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Customization.ipynb PASSED                                  [ 18%]
examples/user_guide/Geographic_Data.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Geographic_Data.ipynb PASSED                              [ 27%]
examples/user_guide/Gridded_Data.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Gridded_Data.ipynb FAILED                                    [ 36%]
examples/user_guide/Introduction.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Introduction.ipynb PASSED                                    [ 45%]
examples/user_guide/NetworkX.ipynb::D:\code\pyviz\hvplot\examples\user_guide\NetworkX.ipynb FAILED                                            [ 54%]
examples/user_guide/Plotting.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Plotting.ipynb FAILED                                            [ 63%]
examples/user_guide/Statistical_Plots.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Statistical_Plots.ipynb PASSED                          [ 72%]
examples/user_guide/Streaming.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Streaming.ipynb PASSED                                          [ 81%]
examples/user_guide/Subplots.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Subplots.ipynb FAILED                                            [ 90%]
examples/user_guide/Viewing.ipynb::D:\code\pyviz\hvplot\examples\user_guide\Viewing.ipynb FAILED                                              [100%]

===================================================================== FAILURES =====================================================================
___________________________________________________________________ test session ___________________________________________________________________
D:\code\pyviz\hvplot\examples\user_guide\Gridded_Data.ipynb
** line 18 col 0: 'numpy as np' imported but unused
To see python source that was checked by pyflakes: D:\code\pyviz\hvplot\examples\user_guide\Gridded_Data.nbsmoke-debug-postmagicprocess.py
To see python source before magics were handled by nbsmoke: D:\code\pyviz\hvplot\examples\user_guide\Gridded_Data.nbsmoke-debug-premagicprocess.py
___________________________________________________________________ test session ___________________________________________________________________
D:\code\pyviz\hvplot\examples\user_guide\NetworkX.ipynb
** line 18 col 0: 'numpy as np' imported but unused
** line 443 col 0: 'matplotlib.pyplot as plt' imported but unused
** line 524 col 4: redefinition of unused 'pygraphviz' from line 275
** line 524 col 4: 'pygraphviz' imported but unused
** line 529 col 8: redefinition of unused 'pydot' from line 279
** line 529 col 8: 'pydot' imported but unused
To see python source that was checked by pyflakes: D:\code\pyviz\hvplot\examples\user_guide\NetworkX.nbsmoke-debug-postmagicprocess.py
To see python source before magics were handled by nbsmoke: D:\code\pyviz\hvplot\examples\user_guide\NetworkX.nbsmoke-debug-premagicprocess.py
___________________________________________________________________ test session ___________________________________________________________________
D:\code\pyviz\hvplot\examples\user_guide\Plotting.ipynb
** line 16 col 0: 'intake' imported but unused
To see python source that was checked by pyflakes: D:\code\pyviz\hvplot\examples\user_guide\Plotting.nbsmoke-debug-postmagicprocess.py
To see python source before magics were handled by nbsmoke: D:\code\pyviz\hvplot\examples\user_guide\Plotting.nbsmoke-debug-premagicprocess.py
___________________________________________________________________ test session ___________________________________________________________________
D:\code\pyviz\hvplot\examples\user_guide\Subplots.ipynb
** line 18 col 0: 'numpy as np' imported but unused
To see python source that was checked by pyflakes: D:\code\pyviz\hvplot\examples\user_guide\Subplots.nbsmoke-debug-postmagicprocess.py
To see python source before magics were handled by nbsmoke: D:\code\pyviz\hvplot\examples\user_guide\Subplots.nbsmoke-debug-premagicprocess.py
___________________________________________________________________ test session ___________________________________________________________________
D:\code\pyviz\hvplot\examples\user_guide\Viewing.ipynb
** line 42 col 9: undefined name 'display'
To see python source that was checked by pyflakes: D:\code\pyviz\hvplot\examples\user_guide\Viewing.nbsmoke-debug-postmagicprocess.py
To see python source before magics were handled by nbsmoke: D:\code\pyviz\hvplot\examples\user_guide\Viewing.nbsmoke-debug-premagicprocess.py
================================================= 5 failed, 6 passed, 22 skipped in 20.49 seconds ==================================================
```

Haven't decided yet what nbsmoke should do about `display()`. I'd like it to complain by default (requiring display to be explicitly imported), but I'm open to suggestions about that. I didn't look at the graphviz/dot bits of the networkx example.

### CODE REVIEW

**Comment by ceball** [comment]
Oops, I see my local copy was not up to date. I'll rebase and cross my fingers...

**Comment by jbednar** [comment]
It looks to me like the intake import should be marked #noqa; even if the import is not required for the notebook to run, intake itself appears to be required, so it doesn't hurt to be explicit in the notebook about that.

**Comment by jbednar** [comment]
Oh, and we always want to import `display` explicitly; I don't like relying on IPython's prior imports.

**Comment by jsignell** [comment]
Thanks this is  good start! I should be able to track down more in my docs sweep.

**Pull request merged**
